package com.sharemyride.model;
// Generated Dec 4, 2018 3:11:26 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserHasRating generated by hbm2java
 */
@Entity
@Table(name = "user_has_rating", catalog = "share_my_ride")
public class UserHasRating implements java.io.Serializable {

	private Integer id;
	private User userByToUser;
	private User userByFromUser;
	private String rating;
	private Date createdDate;
	private Date updatedDate;
	private String createdBy;
	private String updatedBy;
	private String status;
	private String remark;

	public UserHasRating() {
	}

	public UserHasRating(User userByToUser, User userByFromUser, String rating, Date createdDate, Date updatedDate,
			String createdBy, String updatedBy, String status, String remark) {
		this.userByToUser = userByToUser;
		this.userByFromUser = userByFromUser;
		this.rating = rating;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.status = status;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_user")
	public User getUserByToUser() {
		return this.userByToUser;
	}

	public void setUserByToUser(User userByToUser) {
		this.userByToUser = userByToUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_user")
	public User getUserByFromUser() {
		return this.userByFromUser;
	}

	public void setUserByFromUser(User userByFromUser) {
		this.userByFromUser = userByFromUser;
	}

	@Column(name = "rating", length = 45)
	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
