package com.sharemyride.model;
// Generated Dec 4, 2018 3:11:26 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRideHistory generated by hbm2java
 */
@Entity
@Table(name = "user_ride_history", catalog = "share_my_ride")
public class UserRideHistory implements java.io.Serializable {

	private Integer id;
	private UserOfferRide userOfferRide;
	private UserSearchRide userSearchRide;
	private Integer toUserBookedSeatCount;
	private String ratingGiven;
	private Integer amount;
	private Float distance;
	private Date createdDate;
	private Date updatedDate;

	public UserRideHistory() {
	}

	public UserRideHistory(UserOfferRide userOfferRide, UserSearchRide userSearchRide, Integer toUserBookedSeatCount,
			String ratingGiven, Integer amount, Float distance, Date createdDate, Date updatedDate) {
		this.userOfferRide = userOfferRide;
		this.userSearchRide = userSearchRide;
		this.toUserBookedSeatCount = toUserBookedSeatCount;
		this.ratingGiven = ratingGiven;
		this.amount = amount;
		this.distance = distance;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_offer_ride_id")
	public UserOfferRide getUserOfferRide() {
		return this.userOfferRide;
	}

	public void setUserOfferRide(UserOfferRide userOfferRide) {
		this.userOfferRide = userOfferRide;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_search_ride_id")
	public UserSearchRide getUserSearchRide() {
		return this.userSearchRide;
	}

	public void setUserSearchRide(UserSearchRide userSearchRide) {
		this.userSearchRide = userSearchRide;
	}

	@Column(name = "to_user_booked_seat_count")
	public Integer getToUserBookedSeatCount() {
		return this.toUserBookedSeatCount;
	}

	public void setToUserBookedSeatCount(Integer toUserBookedSeatCount) {
		this.toUserBookedSeatCount = toUserBookedSeatCount;
	}

	@Column(name = "rating_given", length = 45)
	public String getRatingGiven() {
		return this.ratingGiven;
	}

	public void setRatingGiven(String ratingGiven) {
		this.ratingGiven = ratingGiven;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Column(name = "distance", precision = 12, scale = 0)
	public Float getDistance() {
		return this.distance;
	}

	public void setDistance(Float distance) {
		this.distance = distance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
