package com.sharemyride.model;
// Generated Dec 4, 2018 3:11:26 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserOfferRide generated by hbm2java
 */
@Entity
@Table(name = "user_offer_ride", catalog = "share_my_ride")
public class UserOfferRide implements java.io.Serializable {

	private Integer id;
	private User user;
	private UserVehicle userVehicle;
	private Date datetime;
	private String fromLatitude;
	private String fromLongitude;
	private String toLatitude;
	private String toLongitude;
	private Date createdDate;
	private Date updatedDate;
	private String createdBy;
	private String updatedBy;
	private String status;
	private String remark;
	private Set<UserRideHistory> userRideHistories = new HashSet<UserRideHistory>(0);
	private Set<UserRideDetails> userRideDetailses = new HashSet<UserRideDetails>(0);

	public UserOfferRide() {
	}

	public UserOfferRide(User user, UserVehicle userVehicle, Date datetime, String fromLatitude, String fromLongitude,
			String toLatitude, String toLongitude, Date createdDate, Date updatedDate, String createdBy,
			String updatedBy, String status, String remark, Set<UserRideHistory> userRideHistories,
			Set<UserRideDetails> userRideDetailses) {
		this.user = user;
		this.userVehicle = userVehicle;
		this.datetime = datetime;
		this.fromLatitude = fromLatitude;
		this.fromLongitude = fromLongitude;
		this.toLatitude = toLatitude;
		this.toLongitude = toLongitude;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.status = status;
		this.remark = remark;
		this.userRideHistories = userRideHistories;
		this.userRideDetailses = userRideDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_vehicle_id")
	public UserVehicle getUserVehicle() {
		return this.userVehicle;
	}

	public void setUserVehicle(UserVehicle userVehicle) {
		this.userVehicle = userVehicle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "from_latitude", length = 45)
	public String getFromLatitude() {
		return this.fromLatitude;
	}

	public void setFromLatitude(String fromLatitude) {
		this.fromLatitude = fromLatitude;
	}

	@Column(name = "from_longitude", length = 45)
	public String getFromLongitude() {
		return this.fromLongitude;
	}

	public void setFromLongitude(String fromLongitude) {
		this.fromLongitude = fromLongitude;
	}

	@Column(name = "to_latitude", length = 45)
	public String getToLatitude() {
		return this.toLatitude;
	}

	public void setToLatitude(String toLatitude) {
		this.toLatitude = toLatitude;
	}

	@Column(name = "to_longitude", length = 45)
	public String getToLongitude() {
		return this.toLongitude;
	}

	public void setToLongitude(String toLongitude) {
		this.toLongitude = toLongitude;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userOfferRide")
	public Set<UserRideHistory> getUserRideHistories() {
		return this.userRideHistories;
	}

	public void setUserRideHistories(Set<UserRideHistory> userRideHistories) {
		this.userRideHistories = userRideHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userOfferRide")
	public Set<UserRideDetails> getUserRideDetailses() {
		return this.userRideDetailses;
	}

	public void setUserRideDetailses(Set<UserRideDetails> userRideDetailses) {
		this.userRideDetailses = userRideDetailses;
	}

}
