package com.sharemyride.model;
// Generated Dec 4, 2018 3:11:26 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "share_my_ride")
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String phone;
	private String email;
	private String company;
	private String image;
	private Date dob;
	private String rating;
	private Integer ratingCount;
	private Integer reviewCount;
	private String gender;
	private Integer wallet;
	private Date createdDate;
	private Date updatedDate;
	private String createdBy;
	private String updatedBy;
	private String status;
	private String remark;
	private Set<UserHasRating> userHasRatingsForToUser = new HashSet<UserHasRating>(0);
	private Set<UserSearchRide> userSearchRidesForUserId = new HashSet<UserSearchRide>(0);
	private Set<UserHasRating> userHasRatingsForFromUser = new HashSet<UserHasRating>(0);
	private Set<UserSearchRide> userSearchRidesForWithUser = new HashSet<UserSearchRide>(0);
	private Set<UserOfferRide> userOfferRides = new HashSet<UserOfferRide>(0);
	private Set<UserVehicle> userVehicles = new HashSet<UserVehicle>(0);

	public User() {
	}

	public User(String name, String phone, String email, String company, String image, Date dob, String rating,
			Integer ratingCount, Integer reviewCount, String gender, Integer wallet, Date createdDate, Date updatedDate,
			String createdBy, String updatedBy, String status, String remark,
			Set<UserHasRating> userHasRatingsForToUser, Set<UserSearchRide> userSearchRidesForUserId,
			Set<UserHasRating> userHasRatingsForFromUser, Set<UserSearchRide> userSearchRidesForWithUser,
			Set<UserOfferRide> userOfferRides, Set<UserVehicle> userVehicles) {
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.company = company;
		this.image = image;
		this.dob = dob;
		this.rating = rating;
		this.ratingCount = ratingCount;
		this.reviewCount = reviewCount;
		this.gender = gender;
		this.wallet = wallet;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.status = status;
		this.remark = remark;
		this.userHasRatingsForToUser = userHasRatingsForToUser;
		this.userSearchRidesForUserId = userSearchRidesForUserId;
		this.userHasRatingsForFromUser = userHasRatingsForFromUser;
		this.userSearchRidesForWithUser = userSearchRidesForWithUser;
		this.userOfferRides = userOfferRides;
		this.userVehicles = userVehicles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 145)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 145)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "company", length = 45)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "image", length = 145)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dob", length = 19)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "rating", length = 45)
	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	@Column(name = "rating_count")
	public Integer getRatingCount() {
		return this.ratingCount;
	}

	public void setRatingCount(Integer ratingCount) {
		this.ratingCount = ratingCount;
	}

	@Column(name = "review_count")
	public Integer getReviewCount() {
		return this.reviewCount;
	}

	public void setReviewCount(Integer reviewCount) {
		this.reviewCount = reviewCount;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "wallet")
	public Integer getWallet() {
		return this.wallet;
	}

	public void setWallet(Integer wallet) {
		this.wallet = wallet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "created_by", length = 145)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 145)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByToUser")
	public Set<UserHasRating> getUserHasRatingsForToUser() {
		return this.userHasRatingsForToUser;
	}

	public void setUserHasRatingsForToUser(Set<UserHasRating> userHasRatingsForToUser) {
		this.userHasRatingsForToUser = userHasRatingsForToUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByUserId")
	public Set<UserSearchRide> getUserSearchRidesForUserId() {
		return this.userSearchRidesForUserId;
	}

	public void setUserSearchRidesForUserId(Set<UserSearchRide> userSearchRidesForUserId) {
		this.userSearchRidesForUserId = userSearchRidesForUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByFromUser")
	public Set<UserHasRating> getUserHasRatingsForFromUser() {
		return this.userHasRatingsForFromUser;
	}

	public void setUserHasRatingsForFromUser(Set<UserHasRating> userHasRatingsForFromUser) {
		this.userHasRatingsForFromUser = userHasRatingsForFromUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByWithUser")
	public Set<UserSearchRide> getUserSearchRidesForWithUser() {
		return this.userSearchRidesForWithUser;
	}

	public void setUserSearchRidesForWithUser(Set<UserSearchRide> userSearchRidesForWithUser) {
		this.userSearchRidesForWithUser = userSearchRidesForWithUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserOfferRide> getUserOfferRides() {
		return this.userOfferRides;
	}

	public void setUserOfferRides(Set<UserOfferRide> userOfferRides) {
		this.userOfferRides = userOfferRides;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserVehicle> getUserVehicles() {
		return this.userVehicles;
	}

	public void setUserVehicles(Set<UserVehicle> userVehicles) {
		this.userVehicles = userVehicles;
	}

}
